# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9efa5728493cf73b8dfddf5f3bbff94988a4aed165202d3da210718d5658b82a85fa578900296944a09f17a7a773910a29a4193bf3671bad8b3e3acfad85d5bf

test:
  secret_key_base: 93fc040ded01922d8fcad9e07210844b67c9275f388e6f63be05155b55585d60b7872a5aaa52c4ad9154ec45c20e445a0bb8d34bc63e93f46b770181d6c9da31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
